# Generated by Django 2.2.28 on 2022-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aqwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqwer',
            name='testfiled1122',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
